### PR TITLE
Tweaks to automatic Pages generation

### PR DESCRIPTION
**Pull request by mwoehlke**
Tweak how GHA runs the build for slightly better performance. Don't include hidden files (i.e. build information/cache) in the Pages artifact. Remove old publication stuff.

### CODE REVIEW

**Review by bruxisma — APPROVED** [review]
:shipit:

**Comment by mwoehlke** [comment]
@bruxisma, thanks! Given Bret is otherwise occupied this week, I think this is simple enough to go ahead and land...

(On a somewhat-unrelated note, please re-PR the typo-checking stuff when you get a chance; thanks!)

**Comment by bruxisma** [comment]
Will do when I've got the time. It's a busy week for me as it's GDC and I'm meeting some folks who are in town to catch up (and Dragon's Dogma 2 released... and I'm still helldiving. I've got my priorities right as you can tell... 🤣)

**Comment by mwoehlke** [comment]
> Will do when I've got the time.

@bruxisma, no worries! Just making sure you know we still want those bits. :slightly_smiling_face:

**Pull request merged**
