### PR TITLE
Add userland field

### LINKED ISSUE #1: Issues with the "Kernel" and "Kernel-Version" attributes
The specification has attributes `Kernel` and `Kernel-Version`.  For `Kernel`, the specification says

> Specifies the name of the operating system kernel required by the package’s components. The value is case insensitive and should follow the output of uname -s. Typical values include "windows", "cygwin", "linux" and "darwin".

The Single UNIX Specification says that the `-s` flag to `uname` causes it to "Write the name of the implementation of the operating system.", saying nothing about the kernel.

Linux is the only OS that draws such a strong distinction between the kernel and the OS as a whole; the kernel of Darwin, for example, is called XNU, but `uname -s` on a Darwin-based system prints "Darwin", not "XNU".

And even the value reported by `uname -s` doesn't necessarily fully describe the platform on which you're running; macOS, iOS, watchOS, and tvOS all use Darwin as the "core operating system", but something that can be used on macOS might not be usable on iOS, for example.

For Linux, you'd have "GNU/Linux", i.e. Linux plus something based on GNU libc, and "Bionic/Linux", better known as "Android", and so on.

Even if `Kernel` were replaced by, for example, `OS` in the names, to indicate the full OS rather than just the OS kernel, a UN\*X-only package running on multiple UN\*Xes wouldn't have a single OS whose name would be "*the* name of the OS required by the package's components" - you might need a list such as `linux,macos,ios,solaris,freebsd`.

And, for `OS-Version`, you'd need minimum versions for multiple OSes.

My inclination would be to remove those attributes from the specification, or deprecate them, and wait until a clear need for them is established, and then, based on the requirements for such an attribute, specify attributes that address those requirements.

### PR DESCRIPTION
**Pull request by dcbaker**
In addition to the kernel and the kernel-version required, it's often useful (especially when cross compiling) to know what userland we're targeting. This is required to differentiate, for example, GNU/Linux from Android/Linux or macOS/Darwin from iOS/Darwin.

I believe with this, the kernel field, and the *-runtime-library fields we can fully represent this information.

Fixes #1

### CODE REVIEW

**Comment by mwoehlke** [comment]
Can you give an example of *when* that would be useful? I guess I can think of examples, but this seems like something that would be more useful to non-software-library components. It's not often that libraries care about the system utilities. (Plus, I'm not sure how you would even determine that; a BSD system for example might have both a BSD *and* GNU userspace installed. Moreover, trying to specify how *complete* a particular userspace is seems like it would be a nightmare.)

**Comment by dcbaker** [comment]
cross compiling from macos/darwin to ios/darwin. they're both darwin, they're both aarch64, but you cant use dependencies from the build machine on the host machine. same problem with linux/glibc -to linux/bionic (aka, android).

**Comment by dcbaker** [comment]
Consider these case cases:
1) your package depends on an apple framework. Frameworks are inherently part of the specific SDK (ios, tvos, macos, etc)
2) your package relies on specific functionality in the android fork of the linux kernel (ashmem, for example).
3) your package doesn't make sense on some variants of an os [(you can't use a macos compiled Qt on ios, for example)](https://doc.qt.io/qt-5/ios.html)
4) you need to link against libraries that are part of a specific userland configuration, but don't provide any finder methods (things like libdevinfo on solaris, you need this if you're using oracle solaris or one of the open solaris derived user lands, but if you're using illumos with gnu then you don't)

**Comment by dcbaker** [comment]
yes, runtime libraries

**Review by bretbrownjr — COMMENTED** [review]
Are there examples of other systems using the term "userland"?

I was under the impression that this was generally captured under the "operating system" umbrella. Obligatory reference to the debates about whether Linux should be called GNU/Linux, etc.

@bruxisma has well-formed thoughts about target identifiers and might have more developed ideas on how to support this use case.

On a more meta level, barring a clean path forward in specific cases, I'm actually OK punting on details like this, especially if there's are `extension` JSON objects that can capture this information as needed.

As I was saying at the Ecosystem Evolution catchup Friday, I'm starting to think the CPS data is mostly for the dependency management systems to communicate requirements to the build systems. Reasonable dependency graph validation by the build system is sensible (barring a user-provide `--force` flag), but I don't think we necessarily need or want every iota or origin information in the CPS data. The dependency management system has to do *some* things to make the work for the build system reasonable.

**Comment by bruxisma** [comment]
To briefly comment: The way apple has actually named the underlying target triplet (or tuplet, if you prefer) for their fork of Clang is inline with what I documented in [P1864](https://wg21.link/P1864). In fact, unless you are using GCC specific aliases for certain targets, nearly everything out there sits in the P1864 definition, save for custom compilers for very old platforms (e.g., the SNES, Atari Jaguar, and other retro computing platforms that have seen a revival through homebrew support over the last 2 decades. Though I would not be surprised if maintainers of these toolchains could be convinced to cleanup their support and finalize on target identifiers 😝)

Some definitions have both an operating system + environment (e.g., windows-gnu and windows-msvc) where environment can mean a slew of things such as runtime, ABI, object file format, executable format, or more. In cases where there is no operating system, the environment takes the lead (e.g., UEFI is not an operating system, but target identifiers do have `uefi` as the last entry in the target, as `uefi-pe` or `uefi-coff` would be superfluous, as UEFI encodes the object file/executable format into its specification)

The reason we use `gnu` for a lot of these targets is because they are using the gnu C library as a runtime. (This is why Rust's `musl` is a separate target that has replaced `gnu` for `musl`)

**Comment by dcbaker** [comment]
The specific case where I'm trying to differentiate using "userland" is things like Android/Linux vs GNU/Linux and some more exotic things (that seem to be finally dying) like Debian's GNU/Kfreebsd and some of the OpenSolaris derivatives that use a GNU userland on top of The OpenSolaris Kernel.

Which is something in Meson we've specifically run into, it's not easy to differentiate that a "dependency" is for Debian/Kfreebsd vs FreeBSD itself. I think we've had some large discussions about how to represent this, so I'm going to close this in favor of some of Izzy's discussion about tuplets, which I think will be more useful.

**Pull request closed without merging**
